[project]
name = "services-optimization"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "psycopg[binary]>=3.2.7",
    "sqlalchemy>=2.0.40",
]
